### ISSUE TITLE
Multiple assume roles

### ISSUE THREAD

**Issue by sstarcher** [broamski/aws-mfa#19]
Maybe it's possible, but I'm not seeing it from the documentation.

It would be nice to be able to have a single long-term that can assume roles into multiple accounts with multiple permissions.

default-long-term, but can easily assume 
* `aws-mfa --assume-role admin --account dev`
* `aws-mfa --assume-role admin --account qa`
* `aws-mfa --assume-role readonly --account dev`

**Comment by broamski** [comment]
Hi @sstarcher this appears to be possible with the `short-term-suffix` option. Take a look a the very last example in the README, this should take care of you! Thanks for using aws-mfa!

**Comment by sstarcher** [comment]
@broamski got ya so what you are suggesting would be 
`aws-mfa --assume-role admin admin --short-term-suffix qa --assume-role arn:aws:iam::123456788990:role/RoleName`

`aws-mfa --assume-role admin admin --short-term-suffix dev --assume-role arn:aws:iam::123456788991:role/RoleName`

I was really hoping to have it less painful for users by having the config for these definitions inside of the .aws/config vs having the user need to know the additional info.

**Comment by broamski** [comment]
I would recommend using profiles or similar:

```
[prod-long-term]
aws_access_key_id = YOUR_LONGTERM_KEY_ID
aws_secret_access_key = YOUR_LONGTERM_ACCESS_KEY
assume_role =  arn:aws:iam::123456788990:role/some-admin-role
```

Then: `aws-mfa --profile prod`

**Comment by sstarcher** [comment]
@broamski sounds good that's what I'm doing I was just hoping to not have to copy the key a dozen times.  Thanks for the assistance.
