### ISSUE TITLE
ModuleNotFoundError: No module named 'config'

### ISSUE THREAD

**Issue by StarryShark** [broamski/aws-mfa#26]
There seems to be a bug in version 0.0.11. I'm getting following error,

```
Traceback (most recent call last):
  File "/usr/local/bin/aws-mfa", line 7, in <module>
    from awsmfa import main
  File "/usr/local/lib/python3.6/site-packages/awsmfa/__init__.py", line 16, in <module>
    from config import initial_setup
ModuleNotFoundError: No module named 'config'
```

Version 0.0.10 is working fine for me. Please check.

I am using Python 3.6.5.

**Comment by sumitgoelpw** [comment]
Thank you @broamski for super quick response and fix. It's working now.

Thank you for creating this tool, it has been beneficial.
