### ISSUE TITLE
Maximum duration is 3600 seconds, is this still the case?

### ISSUE THREAD

**Issue by fgimian** [broamski/aws-mfa#6]
Hey there, thanks for your awesome little script, it's helping us a lot.

I notice you mention that a maximum duration of 3600 is enforced but this doesn't seem to be the case in the code.  I've also seen other tools stating you can keep sessions open for many hours.

In our case, we'd like to keep sessions open for 12 hours or longer to make it easier to work.

Can you kindly clarify the 3600 second duration limit?

Thanks so much!
Fotis

**Comment by broamski** [comment]
If you are assuming an IAM role, temporary credentials are limited to a maximum of 3600 seconds.

If you are generating temporary credentials for an IAM user, temporary credentials are limited to a max lifetime of 129600 seconds (36 hours).

So, if you are not assuming a role, you can provide a value via `MFA_STS_DURATION` or `--duration` that is greater than 3600. I can clear this up a bit in the docs.

Thanks for using `aws-mfa`!

http://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html
http://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html

**Comment by fgimian** [comment]
Really appreciate the reply, thanks so much! :smile:
